CREATE DATABASE quehaceres;

CREATE TABLE list (id SERIAL PRIMARY KEY, name TEXT NOT NULL);

CREATE TABLE todo (
    id SERIAL PRIMARY KEY, 
    description TEXT NOT NULL, 
    favourite BOOLEAN DEFAULT FALSE,
    done BOOLEAN DEFAULT FALSE,
    list INTEGER REFERENCES list(id) ON DELETE CASCADE
);